"""The pure numerical layer of the cellular-automata lab."""

from .grid import Grid, empty_grid
from .measurements import (
    alive_count,
    alive_fraction,
    changed_cell_count,
    has_changed,
    transition_counts,
)
from .random import generate_random_grids, key_from_seed, random_grid, random_rule, random_rules
from .rules import (
    CONWAY,
    HIGHLIFE,
    Rule,
    format_rule,
    int_to_rule,
    masks_to_rule,
    parse_rule,
    rule_to_int,
    rule_to_masks,
    validate_rule,
)
from .simulate import (
    generate_batched_trajectory,
    generate_rule_trajectories,
    generate_trajectory,
    run_batched_until_stable,
    run_steps,
    run_steps_dynamic_with_metrics,
    run_steps_with_metrics,
    run_until_stable,
    run_until_stable_with_metrics,
    simulate,
    simulate_rule,
    simulate_rule_batch,
    simulate_rules,
)
from .step import batched_step, neighbor_count, neighbor_count_jit, step, step_jit

__all__ = [
    "CONWAY",
    "HIGHLIFE",
    "Grid",
    "Rule",
    "alive_count",
    "alive_fraction",
    "batched_step",
    "changed_cell_count",
    "empty_grid",
    "format_rule",
    "generate_batched_trajectory",
    "generate_random_grids",
    "generate_rule_trajectories",
    "generate_trajectory",
    "has_changed",
    "int_to_rule",
    "key_from_seed",
    "masks_to_rule",
    "neighbor_count",
    "neighbor_count_jit",
    "parse_rule",
    "random_grid",
    "random_rule",
    "random_rules",
    "rule_to_int",
    "rule_to_masks",
    "run_steps",
    "run_batched_until_stable",
    "run_steps_dynamic_with_metrics",
    "run_steps_with_metrics",
    "run_until_stable",
    "run_until_stable_with_metrics",
    "simulate",
    "simulate_rule",
    "simulate_rule_batch",
    "simulate_rules",
    "step",
    "step_jit",
    "transition_counts",
    "validate_rule",
]
